import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="w-screen h-screen flex justify-center items-center flex-col">
            <form className="w-2/5 flex flex-col items-center">
                <div className={"w-full p-5"}>
                    <label htmlFor={"drafts"}>Amount of drafts</label>
                    <input type={"number"} className={"float-right"} max={5} min={1} defaultValue={1} id="drafts" />
                </div>
                <div className={"w-full p-5"}>
                    <label htmlFor={"search"}>Second player</label>
                    <input type={"search"} className={"float-right"} id="player" />
                </div>
                <div className={"w-full p-5"}>
                    <label htmlFor={"time"}> Disable time</label>
                    <input type={"checkbox"} className={"float-right"} id={"time"}/>
                </div>
                <Link href="/draft">
                    <a className="border-2 border-indigo-400 rounded-xl px-4 py-2 text-2xl bg-indigo-500 hover:bg-indigo-400 w-fit">
                        Create new draft
                    </a>
                </Link>
            </form>


        </div>
    </div>
  )
}

export default Home
